y = 10
y2 = 10.3
y3 = 7e46

print(type(y))
print(type(y2))
print(type(y3))

b1 = True
b2 = False

# Collection/Array : List, Tuple, Set, Dict

# List
hl = ['parach', 343, 'Adewumi', True, 34.1, ['Boy', 'Girl']]

student_list = ['Adebiyi', 'Aishat', 'Leke', 'Fortune', 'Adewumi', 'Boluwatife']
print(student_list)

print(student_list)
student_list.pop()
print(student_list)

student_list.reverse()
print(student_list)

student_list.sort()
print(student_list)

student_list.reverse()
print(student_list)

print(len(student_list))

# Tuple
student_Tuple = ('Adebiyi', 'Aishat', 'Leke', 'Fortune', 'Adewumi', 'Boluwatife')

# brackets / Braces
# () - curve
# [] - square
# {} - curly
# <> - angle

print(student_Tuple[3])
print(student_Tuple[:3])


# set
student_set = {'Adebiyi', 'Aishat', 'Leke', 'Fortune', 'Adewumi', 'Boluwatife'}
print(student_set)
print(student_list)

for eachitem in student_list:
    print(eachitem)

name = 'John'
concat = 'Hello' + name
print(concat)

# Hello Adebiyi, Welcome to  class